use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// The bundle manifest (`manifest.json`).
///
/// Authoritative descriptor generated at pack time. Contains SHA-256
/// checksums for every other file in the bundle.
/// Spec: sembundle-spec.md §4.
#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub struct Manifest {
    pub spec_version: String,
    pub name: String,
    pub version: String,
    pub source_repo: String,
    pub commit_hash: String,
    pub tag: Option<String>,
    pub created_at: String,
    pub codegraph_version: String,
    /// Optional bundle extensions present (e.g. `["lance"]`).
    /// Spec: sembundle-spec.md §4.2.
    pub extensions: Vec<String>,
    /// Map of bundle-relative file path → SHA-256 hex digest.
    /// Covers every file in the bundle **except** `manifest.json` itself.
    pub checksums: HashMap<String, String>,
}

/// Source metadata embedded in the bundle (`metadata.json`).
///
/// Generated by the packer from CLI arguments.
/// Spec: sembundle-spec.md §5.
#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub struct Metadata {
    pub name: String,
    pub version: String,
    pub source_repo: String,
    pub commit_hash: String,
    pub tag: Option<String>,
    pub language: String,
    pub indexed_paths: Vec<String>,
    pub created_at: String,
}

/// LanceDB index metadata (`lance/metadata.json`).
///
/// Written by the packer when a `lance/` extension is included. The `created_at`
/// field is stamped by the packer to match `manifest.json` `created_at` (spec §11.5).
/// Spec: sembundle-spec.md §9.3.
#[derive(Debug, Serialize, Deserialize)]
pub struct LanceMetadata {
    pub table_name: String,
    pub document_count: u64,
    pub chunk_count: u64,
    pub indexed_paths: Vec<String>,
    pub fts_enabled: bool,
    /// Stamped by the packer to match `manifest.json` `created_at`.
    pub created_at: String,
}
