"""Handles reading/writing codegraph-hub.toml and codegraph-hub.lock."""

from __future__ import annotations

import hashlib
import io
import json
import tarfile
import tomllib
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

import tomli_w

from .bundle_store import (
    BundleInstallError,
    VersionExistsError,
    get_workspace_store,
)

MANIFEST_FILENAME = "codegraph-hub.toml"
LOCK_FILENAME = "codegraph-hub.lock"


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------

@dataclass
class RegistryConfig:
    name: str
    url: str  # base URL, trailing slash stripped


@dataclass
class BundleDep:
    name: str
    version: str
    registry: str  # name of a RegistryConfig


@dataclass
class WorkspaceManifest:
    registries: list[RegistryConfig]
    dependencies: dict[str, BundleDep]  # name -> BundleDep
    verify_key: Optional[str]           # path string, relative to manifest dir, or None

    def get_registry(self, name: str) -> Optional[RegistryConfig]:
        for r in self.registries:
            if r.name == name:
                return r
        return None

    def default_registry(self) -> Optional[RegistryConfig]:
        """Return the first registry, or None if none defined."""
        return self.registries[0] if self.registries else None


@dataclass
class LockEntry:
    name: str
    version: str
    registry_url: str
    sha256: str
    signed: bool
    manifest_checksums: dict[str, str]  # from bundle's own manifest.json checksums field


@dataclass
class LockFile:
    packages: dict[str, LockEntry] = field(default_factory=dict)  # name -> LockEntry


# ---------------------------------------------------------------------------
# Manifest I/O
# ---------------------------------------------------------------------------

def load_manifest(workspace_dir: Path) -> WorkspaceManifest:
    """Load codegraph-hub.toml from workspace_dir. Raises FileNotFoundError if absent."""
    manifest_path = workspace_dir / MANIFEST_FILENAME
    if not manifest_path.exists():
        raise FileNotFoundError(
            f"{MANIFEST_FILENAME} not found in {workspace_dir}. "
            "Run 'codegraph-hub bundle add <pkg>@<version> --registry-url <url>' to create one."
        )

    with manifest_path.open("rb") as f:
        data = tomllib.load(f)

    workspace_section = data.get("workspace", {})
    verify_key: Optional[str] = workspace_section.get("verify_key") or None

    registries = [
        RegistryConfig(name=r["name"], url=r["url"].rstrip("/"))
        for r in data.get("registries", [])
    ]
    registry_names = {r.name for r in registries}
    default_reg_name = registries[0].name if registries else None

    dependencies: dict[str, BundleDep] = {}
    for dep_name, dep_val in data.get("dependencies", {}).items():
        reg_name = dep_val.get("registry") or default_reg_name
        if reg_name is None:
            raise ValueError(
                f"Dependency '{dep_name}' has no registry and no registries are defined."
            )
        if reg_name not in registry_names:
            raise ValueError(
                f"Dependency '{dep_name}' references unknown registry '{reg_name}'. "
                f"Defined registries: {sorted(registry_names)}"
            )
        dependencies[dep_name] = BundleDep(
            name=dep_name,
            version=dep_val["version"],
            registry=reg_name,
        )

    return WorkspaceManifest(
        registries=registries,
        dependencies=dependencies,
        verify_key=verify_key,
    )


def save_manifest(manifest: WorkspaceManifest, workspace_dir: Path) -> None:
    """Write codegraph-hub.toml using tomli_w."""
    data: dict = {}
    if manifest.verify_key:
        data["workspace"] = {"verify_key": manifest.verify_key}
    if manifest.registries:
        data["registries"] = [{"name": r.name, "url": r.url} for r in manifest.registries]
    data["dependencies"] = {
        name: {"version": dep.version, "registry": dep.registry}
        for name, dep in manifest.dependencies.items()
    }

    header = (
        "# codegraph-hub workspace bundle manifest\n"
        "# Run: codegraph-hub bundle sync\n\n"
    )
    content = header + tomli_w.dumps(data)
    (workspace_dir / MANIFEST_FILENAME).write_text(content, encoding="utf-8")


# ---------------------------------------------------------------------------
# Lock file I/O
# ---------------------------------------------------------------------------

def _write_lock(lock: LockFile) -> str:
    """Serialize a LockFile to a readable TOML string with alignment and comments."""
    lines = [
        "# Auto-generated by codegraph-hub. DO NOT EDIT.",
        "# Commit this file to ensure reproducible installs.",
        "",
    ]
    for entry in sorted(lock.packages.values(), key=lambda e: e.name):
        lines.append("[[package]]")
        lines.append(f'{"name":<16} = "{entry.name}"')
        lines.append(f'{"version":<16} = "{entry.version}"')
        lines.append(f'{"registry_url":<16} = "{entry.registry_url}"')
        lines.append(f'{"sha256":<16} = "{entry.sha256}"')
        lines.append(f'{"signed":<16} = {"true" if entry.signed else "false"}')
        lines.append("")
        lines.append("[package.manifest_checksums]")
        for path_key, checksum in sorted(entry.manifest_checksums.items()):
            lines.append(f'"{path_key}" = "{checksum}"')
        lines.append("")
    return "\n".join(lines)


def load_lock(workspace_dir: Path) -> LockFile:
    """Load codegraph-hub.lock. Returns empty LockFile if absent."""
    lock_path = workspace_dir / LOCK_FILENAME
    if not lock_path.exists():
        return LockFile()

    content = lock_path.read_text(encoding="utf-8")
    data = tomllib.loads(content)

    packages: dict[str, LockEntry] = {}
    for pkg in data.get("package", []):
        entry = LockEntry(
            name=pkg["name"],
            version=pkg["version"],
            registry_url=pkg["registry_url"],
            sha256=pkg["sha256"],
            signed=pkg.get("signed", False),
            manifest_checksums=pkg.get("manifest_checksums", {}),
        )
        packages[entry.name] = entry
    return LockFile(packages=packages)


def save_lock(lock: LockFile, workspace_dir: Path) -> None:
    """Write codegraph-hub.lock."""
    (workspace_dir / LOCK_FILENAME).write_text(_write_lock(lock), encoding="utf-8")


# ---------------------------------------------------------------------------
# Resolution helpers
# ---------------------------------------------------------------------------

def _fetch_manifest_checksums(
    registry_url: str, package: str, version: str
) -> dict[str, str]:
    """Download the bundle and extract checksums from its inner manifest.json."""
    url = f"{registry_url}/bundles/{package}/{version}/{package}-{version}.cgbundle"
    with urllib.request.urlopen(url) as response:  # noqa: S310
        bundle_bytes = response.read()

    buf = io.BytesIO(bundle_bytes)
    with tarfile.open(fileobj=buf, mode="r:gz") as tf:
        for member in tf.getmembers():
            parts = Path(member.name).parts
            if len(parts) == 2 and parts[1] == "manifest.json":
                f = tf.extractfile(member)
                if f is not None:
                    inner = json.loads(f.read().decode("utf-8"))
                    return inner.get("checksums", {})
    return {}


def resolve_lock(manifest: WorkspaceManifest, workspace_dir: Path) -> LockFile:
    """Fetch index.json from each registry and build a fresh LockFile.

    For each dependency in the manifest:
    - Fetch <registry_url>/index.json
    - Extract sha256, signed from packages.<name>.bundles.<version>
    - Fetch the bundle and read manifest_checksums from inner manifest.json
    - Build LockEntry

    Raises ValueError if a package+version is not found in the registry.
    """
    packages: dict[str, LockEntry] = {}

    for dep_name, dep in manifest.dependencies.items():
        registry = manifest.get_registry(dep.registry)
        if registry is None:
            raise ValueError(f"Registry '{dep.registry}' not found in manifest")

        registry_url = registry.url
        index_url = f"{registry_url}/index.json"

        with urllib.request.urlopen(index_url) as response:  # noqa: S310
            index_data = json.loads(response.read().decode("utf-8"))

        bundle_entry = (
            index_data
            .get("packages", {})
            .get(dep_name, {})
            .get("bundles", {})
            .get(dep.version)
        )
        if bundle_entry is None:
            raise ValueError(
                f"Package '{dep_name}@{dep.version}' not found in registry '{registry.name}' "
                f"at {registry_url}"
            )

        sha256 = bundle_entry.get("sha256", "")
        signed = bundle_entry.get("signed", False)
        manifest_checksums = _fetch_manifest_checksums(registry_url, dep_name, dep.version)

        packages[dep_name] = LockEntry(
            name=dep_name,
            version=dep.version,
            registry_url=registry_url,
            sha256=sha256,
            signed=signed,
            manifest_checksums=manifest_checksums,
        )

    return LockFile(packages=packages)


def sync_workspace(
    workspace_dir: Path,
    verify_key_path: Optional[Path] = None,
    *,
    reinstall: bool = False,
) -> list[str]:
    """Install all bundles defined in the workspace manifest.

    1. Load codegraph-hub.toml (raise FileNotFoundError if absent, with hint)
    2. Load codegraph-hub.lock if present; if any dep is missing from lock,
       call resolve_lock() to refresh
    3. For each dependency in manifest:
       a. Skip if already installed and not reinstall
       b. Install via BundleStore.install_from_registry()
    4. Save updated lock file
    5. Return list of installed package specs ("name@version")
    """
    manifest = load_manifest(workspace_dir)  # raises FileNotFoundError with hint if absent
    lock = load_lock(workspace_dir)

    # Refresh lock if any dep is missing
    missing = [n for n in manifest.dependencies if n not in lock.packages]
    if missing:
        fresh = resolve_lock(manifest, workspace_dir)
        for name, entry in fresh.packages.items():
            lock.packages[name] = entry

    store = get_workspace_store(workspace_dir)
    installed: list[str] = []

    for dep_name, dep in manifest.dependencies.items():
        if not reinstall and store.resolve(dep_name, dep.version) is not None:
            continue

        lock_entry = lock.packages.get(dep_name)
        if lock_entry is None:
            raise ValueError(
                f"No lock entry for '{dep_name}'. Run 'codegraph-hub bundle lock' first."
            )

        store.install_from_registry(
            dep_name,
            dep.version,
            lock_entry.registry_url,
            verify_key_path=verify_key_path,
        )
        installed.append(f"{dep_name}@{dep.version}")

    save_lock(lock, workspace_dir)
    return installed
