use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// The bundle manifest (`manifest.json`).
///
/// Authoritative descriptor generated at pack time. Contains SHA-256
/// checksums for every other file in the bundle.
/// Spec: cgbundle-spec.md §4.
#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub struct Manifest {
    pub spec_version: String,
    pub name: String,
    pub version: String,
    pub source_repo: String,
    pub commit_hash: String,
    pub tag: Option<String>,
    pub created_at: String,
    pub codegraph_version: String,
    /// Map of bundle-relative file path → SHA-256 hex digest.
    /// Covers every file in the bundle **except** `manifest.json` itself.
    pub checksums: HashMap<String, String>,
}

/// Source metadata embedded in the bundle (`metadata.json`).
///
/// Generated by the packer from CLI arguments.
/// Spec: cgbundle-spec.md §5.
#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub struct Metadata {
    pub name: String,
    pub version: String,
    pub source_repo: String,
    pub commit_hash: String,
    pub tag: Option<String>,
    pub language: String,
    pub indexed_paths: Vec<String>,
    pub created_at: String,
}
